### ISSUE TITLE
Possible cause of failed nodeDef creation

### ISSUE THREAD

**Issue by JavierRefuerzo** [UniversalDevicesInc-PG3/udi-poly-notification#38] opened 2022-04-12 21:42 UTC
This crash happens after saving custom params. Restarting node server appears to fix the issue in most cases.

```
2022-04-12 15:33:41,854 Thread-12  udi_interface      ERROR    udi_interface:write: Exception in thread
2022-04-12 15:33:41,855 Thread-12  udi_interface      ERROR    udi_interface:write: Thread-12
2022-04-12 15:33:41,856 Thread-12  udi_interface      ERROR    udi_interface:write: :
2022-04-12 15:33:41,857 Thread-12  udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2022-04-12 15:33:41,857 Thread-12  udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2022-04-12 15:33:41,861 Thread-12  udi_interface      ERROR    udi_interface:write: self.run()
2022-04-12 15:33:41,862 Thread-12  udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.8/threading.py", line 870, in run
2022-04-12 15:33:41,865 Thread-12  udi_interface      ERROR    udi_interface:write: self._target(*self._args, **self._kwargs)
2022-04-12 15:33:41,866 Thread-12  udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/00:0d:b9:53:30:1c_3/nodes/Controller.py", line 504, in handler_typed_data
2022-04-12 15:33:41,869 Thread-12  udi_interface      ERROR    udi_interface:write: self.write_profile()
2022-04-12 15:33:41,870 Thread-12  udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/00:0d:b9:53:30:1c_3/nodes/Controller.py", line 604, in write_profile
2022-04-12 15:33:41,873 Thread-12  udi_interface      ERROR    udi_interface:write: config_info_nr.append(node.config_info_nr())
2022-04-12 15:33:41,874 Thread-12  udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/00:0d:b9:53:30:1c_3/nodes/Pushover.py", line 209, in config_info_nr
2022-04-12 15:33:41,876 Thread-12  udi_interface      ERROR    udi_interface:write: '<li>Example Network Resource settings for Pushover<ul><li>http<li>POST<li>Host:{0}<li>Port:{1}<li>Path: /send?node={2}&Subject=My+Subject&monospace=1&device=1&priority=2<li>Encode URL: not checked<li>Timeout: 5000<li>Mode: Raw Text</ul>'.format(self.controller.rest.ip,self.controller.rest.listen_port,self.address),
2022-04-12 15:33:41,877 Thread-12  udi_interface      ERROR    udi_interface:write: AttributeError
2022-04-12 15:33:41,877 Thread-12  udi_interface      ERROR    udi_interface:write: :
2022-04-12 15:33:41,878 Thread-12  udi_interface      ERROR    udi_interface:write: 'NoneType' object has no attribute 'ip'
```

**Comment by jimboca** [comment] 2022-04-13 03:07
Thanks, will take a look

**Comment by jimboca** [comment] 2022-04-14 22:10
Duplicate of #34

**Closed** 2022-04-14 22:10 UTC
